### ISSUE TITLE
mincLmerEstimateDF breaks when mincLmer is run without a mask

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#101]
c.o. Rylan

Random voxels are sampled from within the mask for computing the degrees of freedom. If the mask is NULL we get:

lmod <- mincLmerEstimateDF(lmod)
Error in if (file.access(as.character(filenames[i]), 4) == -1) { :
  argument is of length zero

Should we fix to sample purely random voxels, or random voxels near the centre of the image to increase the likelihood of choosing non-bg voxels?

**Comment by jasonlerch** [comment]
Or insist that a mask be used? 


(If we don’t like forcing a mask, then I like the idea of biasing towards the centre of the image)

**Comment by cfhammill** [comment]
I'm generally against constraining the user, but here it probably makes sense. I think users wasting time forgetting their masks is much more likely than users genuinely wishing to run without a mask. In the case they do, they can always generate a mask of 1s from within RMINC.

I'll change it so masks are mandatory and put a note in the docs on how to run without a mask.

**Comment by gdevenyi** [comment]
I vote for always requiring a mask. It's painful to have to re-run a big analysis because you forgot it.

**Comment by cfhammill** [comment]
Gabe if you run into this problem before I fix it you can always add a mask to the object with

maskFile(lmod) <- "mask.mnc"

This can avoid you needing to rerun the analysis
