### ISSUE TITLE
Error in mincLmer for master and develop branches

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#103]
I'm trying to use master/develop because of this bug in the release: https://github.com/Mouse-Imaging-Centre/RMINC/issues/87

But I can't even run mincLmer now:
```R
two = mincLmer(relative_jacobians ~ genotype*time_point_w + gender + (1|mouse_id), data, mask="/opt/quarantine/resources/DorrSteadmanUllmann/MBM_100um/Dorr_2008_Steadman_2013_Ullmann_2013_on_NRXN1a_v1_mask.mnc", parallel = c("snowfall", 8))
Start: 0 0 0
Count: 86 180 127
Start: 0 0 0
Count: 86 180 127
Range: 7.000000 0.000000
Error: $ operator is invalid for atomic vectors
In addition: Warning message:
In mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
```

**Comment by cfhammill** [comment]
Hmm, I've never seen this problem on our end. The error likely suggests the lmer code is hitting an error, I wouldn't be surprised if this is a file handle problem. How many brains are you running? Is the mask properly binarized? How long before the failure?

**Comment by gdevenyi** [comment]
152 brains.

The mask was not properly binarized (used autocrop to reslice it, apparently that doesn't work right...).

Now is, same error.

~30 seconds before failure.

**Comment by cfhammill** [comment]
Can you run a `ulimit -Sn`? If it's reporting < 1200, try setting it to 2000 with `ulimit -Sn 2000`.

**Comment by gdevenyi** [comment]
Was 1024. Set to 2000. Error persists in rstudio.

Run in terminal, works.

**Comment by gdevenyi** [comment]
Quick experiment, run original (with 1024) in terminal.

Result: success.

Diagnosis: rstudio breaks things.

**Comment by cfhammill** [comment]
Did you restart rstudio from the newly ulimited terminal? Also can you run RMINC:::tableOpenFiles() from within Rstudio and report the results? It's possible Rstudio is holding on to extra handles. Granted it may not be file handles at all. I wonder what else Rstudio could interfere with.

**Comment by gdevenyi** [comment]
Yes, I did start rstudio freshly from that ulimited terminal.

Before attempting mincLmer
```R
> RMINC:::tableOpenFiles()
lsof_results
p16600  t0000   tCHR   tDIR  tFIFO  tIPv4   tREG  tunix 
     1      4      1      2      9      1     70      1 
```

After:
```R
> RMINC:::tableOpenFiles()
lsof_results
p16600  t0000   tCHR   tDIR  tFIFO  tIPv4   tREG  tunix 
     1      4      1      2      9      1     84      1 
```

**Comment by cfhammill** [comment]
Hmm, after talks with Jason, it looks like file handles are likely not the real problem. 1024 would not have been enough to run successfully at 8 * (157 + some) fds. Unsure where the problem is coming from.

**Comment by gdevenyi** [comment]
Hrm.

I guess I should try and get Jupyter working with R then...

**Comment by cfhammill** [comment]
I'm hoping that's not necessary. I'll try to reproduce the issue on this side so that I can debug.

**Comment by cfhammill** [comment]
Looks like this had to do with a variable name change being missed during a refactor. Clueless as to why it worked in the terminal for you. Pushing a hot-fix to master now.

**Comment by gdevenyi** [comment]
Wow. That's concerning.

Thanks for the fix!
