### ISSUE TITLE
change output type of mincFDR to gain better access to thresholds

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#106]
Currently in order to extract the F-statistic threshold for 10% FDR from a mincFDR call you have to do something like this:

```
outFDR <- mincFDR(some_lm_run, mask="mask.mnc")
attr(outFDR, "thresholds")[3,1]
```

You should be able to say something like this:
```
outFDR[0.1, "F-statistic"]
```
or something similar... Suggestions?

**Comment by cfhammill** [comment]
The mincFDR object stores q-values, providing programmatic access to the thresholds via `[` seems like the wrong approach. Perhaps we need a thresholds method for mincFDR objects that spits out a table of the thresholds.

**Comment by cfhammill** [comment]
just added a wrapper to `attr(fdr, "thresholds")` in develop: `thresholds(fdr)`

You can access from these exactly how you'd like

``` 
thresholds(fdr)["0.1", "F-statistic"]
```

The quotes on 0.1 are important otherwise R thinks you're doing numeric indexing, rounds .1 to 0 and gives you zero rows of the matrix
