### ISSUE TITLE
anatLmer help doesn't mention anatLmerEstimateDF

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#113]
Is it possible to do FDR correction on anatLmer results?

Currently, mincLmerEstimateDF complains:
```R
Error in if (file.access(as.character(filenames[i]), 4) == -1) { : 
  argument is of length zero
```

**Comment by cfhammill** [comment]
Does `anatLmerEstimateDF()` solve this?

**Comment by gdevenyi** [comment]
Doh, totally didn't notice that exists.

Let's reframe this bug report:

help for anatLmer says:

```
RMINC provides two alternatives: (1) estimating degrees of freedom using the mincLmerEstimateDF function, a
```

**Comment by cfhammill** [comment]
Ahh I see, I'll fix the help to include the right pointer.
