### ISSUE TITLE
anatLmerEstimateDF doesn't modify input object

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#115]
mincLmerEstimateDF modifies its input object to add degress of freedom estimate

anatLmerEstimateDF instead returns the object with the DOF added, which means it must be saved

Just a consistency difference.

**Comment by cfhammill** [comment]
Are you sure the `mincLmerEstimateDF` actually does this?

For example 

```
x <- 5
add_df <- function(obj){ attr(obj, "df") <- "1"; obj }
add_df(x)
x
```
Has the desired effect of not modifying the original object.

**Comment by gdevenyi** [comment]
uh, perhaps my wording is wrong.

I mean this.

How I use mincLmerEstimateDF
```R
mincLmerEstimateDF(results)
```

How I have to use anatLmerEstimateDF
```R
results <- anatLmerEstimateDF(results)
```

**Comment by cfhammill** [comment]
Yes I understand. The example above illustrates that setting attributes within a function call should not effect the source object. I'm perplexed that `mincLmerEstimateDF` actually modifies `results`. The code for the two functions are almost identical...

**Comment by gdevenyi** [comment]
Oh, okay. This is my memory of how I used to do it, perhaps the code changed recently.

I checked with someone who's using the latest code and it now does it as you expect.

Sorry for the noise!
