### ISSUE TITLE
anatMatrix api awkwardness

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#122]
I want to add an index column to my anatMatrix - since various other operations (e.g., throwing away groups with too few members to fit) might change the indexing of my actual dataframe, which I sadly can't feed to anatLm, I'd rather `join` than `cbind` ...

After `as_tibble . anatCombineStructures . anatGetAll`, `mutate(., index=my_df$index)` still fails:

```
Error: matrix as column is not supported
```

The problem isn't my_df$labels (a vector of numbers) -- `labels=1` still breaks in the same way.

Thoughts?

**Comment by bcdarwin** [comment]
Solution for now is to use as.data.frame -- as_tibble and as_data_frame aren't implemented and the default implementations are broken as shown above.

**Comment by cfhammill** [comment]
Looks like `tibble` uses a custom c++ fiunction for matrix coercion which does not play well with attributes (go figure). I'll file a bug report.
