### ISSUE TITLE
propagate errors in parallel fitting procedures?

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#127]
Sometimes when model fitting fails (e.g., due to inadequate memory, jobs being killed, the fit itself failing), you get:

```
Error in result_fleshed_out[mask_vol > 0.5, ] <- result : c("local", 4))
  number of items to replace is not a multiple of replacement length
```

and if you're lucky also

```
In addition: Warning message:
In parallel::mclapply(...) :
  all scheduled cores encountered errors in user code
```

It would be neat if the first message didn't occur (at least by itself) when the second shows what has really gone wrong, and if the errors were displayed (or at least some way was given to retrieve them).  Ideally the errors would be re-raised in the calling process, but I guess this might not be too easy ...

**Comment by cfhammill** [comment]
Seems like I could just walk the results and checking for class "try-error", if found re-throw.

It's a shame there isn't an eager failing version of mclapply... it waits til the end and throws a warning

**Comment by cfhammill** [comment]
Fixed in develop
