### ISSUE TITLE
Mention MINC_FILE_CACHE_MB in case of memory issues

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#128]
Trying to use the local parallel code, running it without parallel the model works, running it with parallel:
```R
> vs<-mincLmer(jacobians3mm~Status*Timepoint+Age+Sex+(1|id)+(1|Site), data=data, mask="model_iso1mm.analysis.mnc", REML=FALSE, safely=TRUE, parallel = c("snowfall",4))
Range: 4.000000 0.000000
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dio.c line 551 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Z.c line 1375 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
/opt/quarantine/minc-toolkit/1.9.11/src/minc-toolkit-v2/libminc/libsrc2/hyper.c:594 (from MINC2): HDF5 function H5Dread failed
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dio.c line 173 in H5Dread(): can't read data
    major: Dataset
    minor: Read failed
  #001: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dio.c line 551 in H5D__read(): can't read data
    major: Dataset
    minor: Read failed
  #002: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dchunk.c line 1872 in H5D__chunk_read(): unable to read raw data chunk
    major: Low-level I/O
    minor: Read failed
  #003: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Dchunk.c line 2902 in H5D__chunk_lock(): data pipeline read failed
    major: Data filters
    minor: Filter operation failed
  #004: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Z.c line 1375 in H5Z_pipeline(): filter returned failure during read
    major: Data filters
    minor: Read failed
  #005: /opt/quarantine/minc-toolkit/1.9.11/src/build/HDF5/src/H5Zdeflate.c line 125 in H5Z_filter_deflate(): inflate() failed
    major: Data filters
    minor: Unable to initialize object
/opt/quarantine/minc-toolkit/1.9.11/src/minc-toolkit-v2/libminc/libsrc2/hyper.c:594 (from MINC2): HDF5 function H5Dread failed
Warning in mclapply(seq_len(n), do_one, mc.preschedule = mc.preschedule,  :
  all scheduled cores encountered errors in user code
Error: $ operator is invalid for atomic vectors
```

**Comment by cfhammill** [comment]
My first guess is memory - how many files are you running? I bet you're filling your RAM, things are getting swappy and then HDF5 doesn't want to read any more data. 

mincLm(er) should be lean on memory, I think the problem is related to the big problem we
had with large mincAverage calls. This if I'm remembering correctly is due to an on-the-fly decompressor eagerly loading far too much into ram.

Vlad mentioned there is a system variable to disable this behaviour (or more ideally limit it). Can't remember which and haven't had a chance to experiment yet.

**Comment by gdevenyi** [comment]
It's human DBM with 70 1x1x1 scans, user reports there doesn't seem to be swapping.

I will ask them to test with that  set to something small and see if that has an impact.

**Comment by cfhammill** [comment]
That doesn't sound like it should be an issue but to be honest I've never tried. I know with 4 cores and a couple hundred scans you will likely hit the problem I mentioned. 

I would recommend running the single core case (it's not threaded so that's not an issue). And monitoring the memory use. If 4x that amount would swamp their system then I bet that's the issue.

**Comment by mcvaneede** [comment]
Just in case, this was the MINC-Users thread on the memory issue:

http://www.bic.mni.mcgill.ca/pipermail/minc-users/2016-December/004575.html

**Comment by gdevenyi** [comment]
@mcvaneede Thanks, I had previously read that thread. Indeed reducing MINC_FILE_CACHE_MB to a small value fixes the local parallel run.

Perahps this should be documented somewhere, or have it set by default for local parallel runs?

**Comment by cfhammill** [comment]
Awesome, thanks Gabe. What did you set MINC_FILE_CACHE_MB to? And did you get a sense for how much longer it took? I think picking a sensible default might be challenging (current MINC_FILE_CACHE_MB / ncores maybe).

**Comment by gdevenyi** [comment]
I set it (very) conservatively to MINC_FILE_CACHE_MB=1. (This was on a 16GB machine)

I don't have a sense of relative speed because before we were running single threaded and after the change we could do 8 threads locally. Also, someone else was doing the running.

**Comment by cfhammill** [comment]
Ok, thanks Gabe, I'll try to run some experiments in the nearish future to look at the memory dynamics. If that env var is behaving nominally the upper limit for running a mincLm should be approximately

(x * y * z * 8: double file size) * (2 * coef + 3: columns output matrix) + (y * z * n * 8: slice buffer) + (n * 1024 * cache: file cache) bytes. 

Each core would require this amount of memory unless I did some work to have each core allocate a smaller output buffer (the code may already do this but I don't think so).

**Comment by vfonov** [comment]
FYI: MINC_FILE_CACHE_MB is per minc2 file: https://github.com/BIC-MNI/libminc/blob/develop/libsrc2/volume.c#L224 
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetCache

**Comment by cfhammill** [comment]
Thanks Vlad, I suspected so. RMINC is currently a bit naive in that it has every file open simultaneously while performing voxel-wise calculations. This problem gets compounded in the multicore case.
