### ISSUE TITLE
Update install docs to include gfortran directions for mac

### ISSUE THREAD

**Issue by publicjo** [Mouse-Imaging-Centre/RMINC#129]
Hi,
I wanted to know if there were specific instructions/issues with installing RMINC on a macOS (Sierra 10.12.2)? I successfully installed minc toolkit but performing this:

git clone https://github.com/Mouse-Imaging-Centre/RMINC.git RMINC
R CMD INSTALL RMINC --configure-args='--with-build-path=/opt/minc/'

==> cloning gets ok of course
however the installation of RMINC yielded a few error messages

clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c minc_anova.c -o minc_anova.o
minc_anova.c:109:10: warning: incompatible pointer types assigning to 'double *' from 'double **'; dereference with *
      [-Wincompatible-pointer-types]
  buffer = create_slice_buffer(filenames, sizes);
         ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           *
minc_anova.c:121:47: warning: incompatible pointer types passing 'double *' to parameter of type 'double **'; take the address with &
      [-Wincompatible-pointer-types]
    fill_slice_buffer(filenames, sizes, hvol, buffer, v0);
                                              ^~~~~~
                                              &
./slice_loop.h:33:19: note: passing argument to parameter 'buffer' here
                              double **buffer,
                                       ^
minc_anova.c:132:39: warning: incompatible pointer types passing 'double *' to parameter of type 'double **'; take the address with &
      [-Wincompatible-pointer-types]
  free_slice_buffer(filenames, sizes, buffer);
                                      ^~~~~~
                                      &
./slice_loop.h:43:19: note: passing argument to parameter 'buffer' here
                              double **buffer);
                                       ^
minc_anova.c:88:7: warning: unused variable 'num_files' [-Wunused-variable]
  int num_files;
      ^
minc_anova.c:86:7: warning: unused variable 'i' [-Wunused-variable]
  int i, v0, v1, v2;
      ^
5 warnings generated.
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c minc_apply.cpp -o minc_apply.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c minc_cpp.cpp -o minc_cpp.o
minc_cpp.cpp:38:7: warning: unused variable 'read_result' [-Wunused-variable]
  int read_result;
      ^
1 warning generated.
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c minc_reader.c -o minc_reader.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c modelling_functions.c -o modelling_functions.o
modelling_functions.c:738:15: warning: assigning to 'char *' from 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
  method_name = CHAR(STRING_ELT(method, 0));
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
modelling_functions.c:714:32: warning: unused variable 'num_files_right' [-Wunused-variable]
  int                num_files,num_files_right,num_files_left;
                               ^
modelling_functions.c:709:30: warning: unused variable 'hvol_left' [-Wunused-variable]
  mihandle_t         *hvol, *hvol_left,*hvol_right,hmask;
                             ^
3 warnings generated.
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c slice_loop_functions.c -o slice_loop_functions.o
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/opt/minc//include/ -I/Users/vfonov/src/build/minc-toolkit-itk3/external//opt/minc/include -I/opt/minc/include -I/opt/minc/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.3/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c vertex_modelling.c -o vertex_modelling.o
vertex_modelling.c:30:28: warning: unused variable 'k' [-Wunused-variable]
  int    p,n,nVertices,i,j,k,mmatrix_rows,mmatrix_cols;
                           ^
1 warning generated.
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o RMINC.so RcppExports.o anat_summaries.o minc2_lib_reg.o minc2_read.o minc2_support.o minc2_write.o minc_anova.o minc_apply.o minc_cpp.o minc_reader.o modelling_functions.o slice_loop_functions.o vertex_modelling.o -L/opt/minc//lib/ -Wl,-rpath,/opt/minc//lib/ -L/Users/vfonov/src/build/minc-toolkit-itk3/external/opt/minc/lib -L/opt/minc/lib -L/opt/minc/lib -Wl,-rpath,/opt/minc/lib -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -lminc2 -lm -ldl -lz -lhdf5 -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/Users/vfonov/src/build/minc-toolkit-itk3/external/opt/minc/lib'
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RMINC.so] Error 1
ERROR: compilation failed for package ‘RMINC’
* removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RMINC’

Any idea?

thanks a lot,
Josselin Houenou

**Comment by cfhammill** [comment]
Hi Josselin 

This is a pretty common problem, I ought to put it in the install notes. You are missing gfortran, a fortran
compiler that comes standard with the gnu compiler collection (gcc) used on most linux systems. 

To get gfortran you can either install it directly from source or install gcc with homebrew. If you have brew already on your mac just run `brew install gcc` from a terminal. If not, install homebrew first then run the preceding command.

Then to make sure you can use it build R packages, open a bash terminal and run:

```
mkdir $HOME/.R/ ## Ignore the error if this directory already exists
touch $HOME/.R/Makevars
echo 'FLIBS=-L/usr/local/Cellar/gcc/5.3.0/lib/gcc/5' >> $HOME/.R/Makevars
```
You may need to fiddle with the FLIBS path if your version of gcc isn't 5.3.0
This sets the default location for fortran libraries.

**Comment by publicjo** [comment]
Thanks a lot, that works perfectly fine now :-)

2017-01-31 20:47 GMT+01:00 Chris Hammill <notifications@github.com>:

**Comment by cfhammill** [comment]
Glad to help! Re-opening to remind me to update the docs.
