### ISSUE TITLE
`columns` argument of mincFDR doesn't return the right columns ...

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#132]
... it just returns the first `num(columns)` columns with 'improved' names, instead of the ones requested.

**Comment by cfhammill** [comment]
Looks like an unfortunate swap of `columns[i]` for `i` itself at a few locations in `mincFDR.mincMultiDim`
should be straight-forward to fix

**Comment by cfhammill** [comment]
should be fixed in develop
