### ISSUE TITLE
Anatomy volume min/max in launch_shinyRMINC()

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#134]
Is there a way to set the minimum and maximum value to use for the anatomy volume using launch_shinyRMINC()? I'm currently loading a volume who's min and max are:

Min:               -465.0913658
Max:               39755.12603

And this shows up as a fully grey background for the stats that are overlaid.

**Comment by cfhammill** [comment]
Can you point me to this file for testing?

**Comment by cfhammill** [comment]
Fixed in develop
