### ISSUE TITLE
non-parametric vertex-wise statistics

### ISSUE THREAD

**Issue by vsteiger** [Mouse-Imaging-Centre/RMINC#137]
hi all,

I'm using RMINC for vertex-wise analyses of shape data. So far I have only applied vertexLM but I would like to run a more robust non-parametric approach. Is there a non-parametric approach (e.g. randomize or TFCE from FSL, monte carlo simulation from FreeSurfer) implemented in RMINC or soon to come?

Best,

Vivian

**Comment by cfhammill** [comment]
Hi Vivian, yes I just wrote functionality for doing randomization tests for TFCE and linear models. Should be releasing soon.

**Comment by vsteiger** [comment]
hi chris, great news. I'd be happy to (beta)-test...just in case ;-)

**Comment by cfhammill** [comment]
Excellent, thanks!

You can try it out now if you do 

```
devtools::install_github("Mouse-Imaging-Centre/RMINC", ref = "develop")
```

Usage is something like:

```
lmod <- mincLm(files ~ covs, data = frame)
randomization_dist <- mincRandomize(lmod)
randomization_dist_tfce <- mincTFCE(lmod)

thresholds(randomization_dist)
thresholds(randomization_dist_tfce)
```

Both results objects store the standard object the mincLm or mincLm after tfce, the randomization distribution of maximal statistics, and the args used to call the function. Documentation for these functions can be found with the usual `?`

This will take a long time without parallelization - to parallelize locally pass `parallel = c("local", <ncores>)`

If you have a cluster set up you can run `parallel = c("", <a big number>)`

**Comment by cfhammill** [comment]
Whoops just re-read your question - currently we don't have TFCE implemented for vertex data, but I could trivially add randomization for vertexLm objects.

**Comment by gdevenyi** [comment]
+1 for vertex TFCE!

**Comment by cfhammill** [comment]
I'll open that as a new issue

**Comment by cfhammill** [comment]
the bones of vertexTFCE have been written, should have a rough version available for testing early next week.

**Comment by cfhammill** [comment]
Released
