### ISSUE TITLE
VertexTFCE

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#138]
Implement a vertex TFCE

Seems easy enough.

**Comment by vsteiger** [comment]
hurray

**Comment by vsteiger** [comment]
hi chris, is there a vertexTFCE version I could test?

**Comment by cfhammill** [comment]
I'm working on it - I have a new implementation that should be pretty fast. Our voxel version is pretty inefficient so I implemented one to work on arbitrary neighbourhood graphs and regression testing it against ours and fsl's. The fun part is all three algorithms disagree on what the right answer.

The correlation between the output volumes is:
 new  <-> old = .76
 old <-> fsl  = .85
new <-> fsl = .83

So I need to do some more testing and tuning to make sure everything is being computed correctly.

**Comment by cfhammill** [comment]
Hi Vivian, it's written and regression testing favourably now. I'll make it available early next week for testing.

**Comment by vsteiger** [comment]
Hey chris, great news...regarding regressions,it would be interesting to compare the TFCE solution (https://github.com/trislett/TFCE_mediation) with the vertexTFCE implementation. If you'd be interested in that I can share my results

**Comment by cfhammill** [comment]
I have been testing against TFCE mediation, and I've been in contact with Tristram Lett, the author about our respective algorithms, there may be one last piece of the story, which is weighting vertices by their associated area, but that would be a pretty trivial add. Everything is regressing perfectly now, our algorithm is slower than TFCE_mediation but still quite fast.

**Comment by cfhammill** [comment]
The area weighting has been added, and the randomization test written, just need to do some validation and we should be in business.

**Comment by vsteiger** [comment]
I'm curious about the implementation and to test it with additional data

**Comment by gdevenyi** [comment]
@vsteiger vertexTFCE works on the develop branch (for me).

Now I have to wrap my head around t-values of 860,000.....

**Comment by cfhammill** [comment]
Does the map look cluster enhanced? I have no strong sense of the expected magnitude of the enhanced statistic. When I benchmarked against some of Matthijs work the 95th quantile was in the 200 range, but each voxel contributes .0002 mm^3 to the cluster size as opposed to 2 mm^2.

**Comment by gdevenyi** [comment]
This is my first look at cluster enhanced results. It's also on a dataset with super strong results to start with.

I'm going to run it on something more plain to examine how it acts.

So far, it runs on the cluster very quickly.

**Comment by cfhammill** [comment]
caught a substantial bug in the area weighting code see commit dabad877cf2d7285afb5dd4b809a14d2a31f2486. Should be fixed now, added a really lame test for the basic vertexTFCE, need to add a few more then release.

**Comment by gdevenyi** [comment]
Only 186,000 now :)

**Comment by cfhammill** [comment]
Hi @vsteiger, just issued a release with vertexTFCE and randomization tests, let me know if you run into any problems.
