### ISSUE TITLE
vertexTFCE, allow one weight file per subject?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#144]
This I think is just a further generalization of the option allowing ``surface`` to define the local weights.

Rather than having RMINC calculate the areas using the surface, I'd like to provide the local surface area measures (as calculated by the Voronoi method, provided by CIVET).

In surfaces with more uneven triangulation the Voronoi method provides a better surface area estimate than the simple area.

**Comment by cfhammill** [comment]
Hi Gabe, I think for a singular voronoi tessellation it's pretty to trivial to implement on the user side: 
Just do `weights = as.numeric(readLines("voronoi.txt"))`

I had considered the multi-subject case but thought that it didn't really make any sense. Individuals don't contribute directly to the TFCE stat, only through the unifying statistic map. So one tessellation per stats map maybe, but not per subject. Does that make sense, or can you think of a use case where each individual would get a different weighting (maybe some exercise in what would the enhancement look like had it been run on each individual surface?)

**Comment by gdevenyi** [comment]
Maybe I'm misinterpreting ``surfaces``? 

```
For the matrix and vertexLm cases, either a single surface object may be passed and used for each individual, or a vector of file names
```

Does that say I can provide one surface per subject? Or am I misinterpreting that sentence?

**Comment by cfhammill** [comment]
I guess I did add that ability, but again I don't think it makes any sense to use it. For the vertexLm case it would be one surface per statistic (not subject), and for the matrix case it would be one per column (whatever the columns are).

**Comment by gdevenyi** [comment]
Okay, that makes more sense. I didn't see why one surface per subject made sense since they "should" all correspond for comparisons to make sense.
