### ISSUE TITLE
RMINC/1.4.4.0 mincLmer cannot find function checkConv

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#148]
```
genotype_age_interact = mincLmer(orig_jacobians ~ genotype*age + gender + (1|mouse_id), filtered.data, mask="mask.mnc")
Number of Volumes: 187
Number of slabs: 86
In slab: 0 1 2 3 4 5 6 
Error in mincApplyRCPP(lmod$fr[, 1], optimizer_fun, mincLmerList = mincLmerList,  : 
  could not find function "checkConv"
```

**Comment by gdevenyi** [comment]
Looks like you're relying on a newly added function? Your dependencies don't specify a version.

https://github.com/Mouse-Imaging-Centre/RMINC/commit/b19707ccce6851c3f532a7bf2a0a83d36534967f

**Comment by cfhammill** [comment]
Yes, the new version exports checkConv, which makes CRAN check happy. I'll update the dependency list.

**Comment by cfhammill** [comment]
Added version dep in develop
