### ISSUE TITLE
Use "tissue type" in anatSummarize?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#149]
We renamed "tissue type" to "tissueType" to ensure it wasn't spaces
```R
volCombined <- anatSummarize(vol, summarize_by = "tissueType", defs = "/data/chamal/projects/colleen/FAT/twolevel-MAGeT/DSUR_40micron_R_mapping_version2_cp.csv")
Error: Unknown variables: tissueType.
```
We'd like to get a summary of GM/WM instead of the hierarchy.

**Comment by cfhammill** [comment]
Yup, small bug internally passing bool instead of col name. Trivial fix I think

**Comment by cfhammill** [comment]
Fixed in develop
