### ISSUE TITLE
Option to ignore NA values in mincSummary functions

### ISSUE THREAD

**Issue by mfriedel** [Mouse-Imaging-Centre/RMINC#15]
mincSummary should have an option to ignore NAs. The default is that this option will NOT be used. If it is used, then any NA values in the data will be ignored when mean, sum, sd, or var are calculated. This should mirror the default R behaviour. 

If NAs are not ignored, and there are NAs in the data, mincSummary should give a message to the user, rather than simply ignoring the NA values.

**Comment by cfhammill** [comment]
Minc files don't support NAs as R has them (as far as I know), so this feature shouldn't be necessary. I will reopen if we can find a counter-example.
