### ISSUE TITLE
mincLmerEstimateDF fails when NAs in original data

### ISSUE THREAD

**Issue by jasonlerch** [Mouse-Imaging-Centre/RMINC#150]
Error is the following:

Error in model.frame.default(data = original_data, drop.unused.levels = TRUE,  : 
  variable lengths differ (found for 'TimeBetweenTests')

Happens when the original formula contains variables with NA in them. mincLmer will correctly strip out NAs, but save the original data (containing NAs) in its resulting object's attributes. These are then queried by mincLmerEstimateDF, but combined with the list of files actually used by mincLmer, thus causing the dimension mismatch.

**Comment by cfhammill** [comment]
Shouldn't be too hard to fix, I think there is enough information in lmerList to determine which obs are getting removed. If I remember correctly we can't pass to model matrix directly to lmerTest. Seems like I could probably do a tagged inner_join on the filenames from lmerList$fr[,1] unless there's an easier way.

**Comment by cfhammill** [comment]
Fixed in develop.
