### ISSUE TITLE
Convert BatchJobs -> batchtools

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#153]
NFS+sqlite flakiness is driving my crazy. Batchtools uses `data.table`s in memory to manage the registry instead of an external sqlite db.

**Comment by gdevenyi** [comment]
I haven't had NFS+sqlite issues with NFSv4.1 with BatchJobs, however, I have with Firefox, so I totally endorse this :)

**Comment by gdevenyi** [comment]
With more users using it I'm running into this now:
https://github.com/tudo-r/BatchJobs/issues/58

Will stages.queries or fs.timeout suggestions apply to RMINC if I try them?

**Comment by cfhammill** [comment]
Yes if you set them in your config. Although in my experience it hasn't fixed anything. Staged queries is now TRUE by default, and in earlier experience setting a high fs.timeout did nothing, although the experiments weren't super rigorous, we had a scheduler upgrade the week after that had seemed to fix this, but now it's back.

**Comment by cfhammill** [comment]
Implemented in dev, release soon
