### ISSUE TITLE
Feature Idea/Request: anatVertexGetAll like anatGetAll

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#163]
Currently, if one wants to use a parcellation of a surface in CIVET, you need to run it with -surface-atlas option, and then parse the .dat files into a CSV for eventual loading into RMINC (for example https://github.com/CobraLab/documentation/wiki/Average-Thickness-and-Surface-Area-from-AAL-atlas-CIVET)

If you want a different parcellation, you need to re-run a portion of the pipeline.

It occurs to me that this atlas application could be done post-hoc similar to anatGetAll by supplying the vertex-wise files for subjects and an atlas file.

**Comment by cfhammill** [comment]
Probably a good idea - although simple enough to do with what's available now:

```
vt <- vertexTable(files)
summaries <- apply(vt, 2, function(col) tapply(col, atlas, mean))
```

**Comment by gdevenyi** [comment]
Totally doable for R wizards, I still have a lot of trouble groking R :)

**Comment by cfhammill** [comment]
can't grok 'em all unfortunately - but yeah worth making convenient for sure.

**Comment by gdevenyi** [comment]
Hi, following up here, we have an application where we'd like to generate arbitrary summaries (mean, stddev, etc) in the AAL regions. I'd like to just use the hacky version, however I'm not sure how I would format the atlas object in your example.

Thanks for the help...

**Comment by cfhammill** [comment]
Let's assume that you've got a matrix of 35000 vertex label files with 10 subjects. The matrix should be 35000 x 10, if you have an AAL label set in R as a length 35000 vector, then the code above should work (actually I think you need to wrap `atlas` in `list` - `list(atlas)`)

`apply(_, 2, f)` applies `f` to each column. `tapply(x, list(g), s)` groups `x` by `g` and applies `s` to each. 

I'm working on a release now, I'll try to have this included.

**Comment by cfhammill** [comment]
Looks like we actually have this already, `anatApply` does the `tapply` for you after you've loaded the vertexTable into memory. I'll deprecate `anatApply` renaming it to `atlasApply` and make it compatible both with anat and vertex data.

**Comment by gdevenyi** [comment]
Hurrah :+1:
