### ISSUE TITLE
Bad checking for MINC_PATH in build script

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#164]
The newest MINC debian packages package MINC into

/opt/minc/VERSION

Current RMINC build scripts do a
```
[0;32m    mincvm-virtualbox: checking Checking for /opt/minc/... yes[0m
[0;32m    mincvm-virtualbox: configure: MINC_PATH set to /opt/minc[0m
```

But the install was actually at /opt/minc/1.9.15, so RMINC build fails.

**Comment by cfhammill** [comment]
I noticed this when Vlad changed the default install path, I'll need to either convert to cmake or fix up the build script to search opt/minc more deeply. For now it can be fixed by setting $MINC_PATH (I think) or using --with-build-path

**Comment by vfonov** [comment]
I suggest checking environment variable MINC_TOOLKIT to determine location of the toolkit, and if it's empty - check /opt/minc_itk4 /opt/minc /usc/local/bic etc...

**Comment by cfhammill** [comment]
closing, it honours --with-build-path properly and $MINC_PATH
