### ISSUE TITLE
vertexLmer and vertexTable can't handle filenames with factor datatype

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#166]
When users define their input files (displacements, surface area, CT, etc) in their CSVs, the columns class type is often "factor".

In vetexLm that seems to be silently converted to character and runs fine.

Trying to run vertexTable or vertexLmer on these results in the error:
```R
Error in read.table(filenames[1]) : 
  'file' must be a character string or connection
```

A quick as.character() conversion resolves the issue.

**Comment by cfhammill** [comment]
one quick fix is to set `options(stringsAsFactors = FALSE)` which should really be the default. 
But fair point, I'll put a conditional cast to character in `vertexTable`, fix may be more involved for lmer but I'll look in to it.

**Comment by gdevenyi** [comment]
A check and a clear error for the user is okay with me too, if lmer can't be easily fixed.

**Comment by cfhammill** [comment]
This should be fixed in dev. I added a factor->character conversion in `vertexTable` which should also fix`vertexApply` and `vertexLmer`.
