### ISSUE TITLE
Idea: Dynamically scale memory request for parallel jobs based on number of jobs

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#171]
*If* I understand the parallel code correctly, if I specify more jobs, each job is actually smaller (in terms of number of voxels/vertices/volumes) that it processes.

If this is the case, then the memory load per job decreases.

This is particularly relevant for the CIC cluster, where jobs below a certain size can sneak into workstations

**Comment by cfhammill** [comment]
In the vertex/anat cases this is probably true, not so for the minc versions, MINC_FILE_CACHE again I think. Walltime and memory can be set on the fly with:

```
BatchJobs::setConfig(
  list(default.resources = 
         list(nodes = 1, vmem = "8G", walltime = "02:00:00")))
```

**Comment by cfhammill** [comment]
I think I'm going to leave this up to the user unless there is outcry.
