### ISSUE TITLE
develop: summary_type fails for options other than "fixef"

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#175]
```R
lmersummaryoutput = anatLmer(~ gender + tbv + genotype*age + age_2 + (age|mouse_id), filtered.data, filtered.data$summary, summary_type="fixef")
There were 46 warnings (use warnings() to see them)
```

```R
> lmersummaryoutput = anatLmer(~ gender + tbv + genotype*age + age_2 + (age|mouse_id), filtered.data, filtered.data$summary, summary_type="anova")
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
In addition: There were 46 warnings (use warnings() to see them)
> lmersummaryoutput = anatLmer(~ gender + tbv + genotype*age + age_2 + (age|mouse_id), filtered.data, filtered.data$summary, summary_type="both")
Error in dimnames(x) <- dn : 
  length of 'dimnames' [2] not equal to array extent
In addition: There were 46 warnings (use warnings() to see them)
```

**Comment by cfhammill** [comment]
Is this anat specific?

**Comment by gdevenyi** [comment]
Uh, not sure. I'm only interested in this output for the anat currently...

**Comment by cfhammill** [comment]
ok, in either case I will look in to it. I'll try to have a fix no later than Thursday.

**Comment by gdevenyi** [comment]
Thanks, we really appreciate it!

**Comment by cfhammill** [comment]
mincLmer was fine, but anat had some crufty old code for name setting and stat type lookup. Should be fixed by my most recent commits.

**Comment by jasonlerch** [comment]
Who are you calling crufty??

He he he

________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.

**Comment by gdevenyi** [comment]
Fixed!

**Comment by cfhammill** [comment]
Hurray!
