### ISSUE TITLE
Shiny "Right-Click -> Save Image" has some weird broken directory/filename default in rstudio

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#177]
Doing this operation hangs the file dialog for a long time, eventually throws an error about not being able to access a directory.

After this, you can delete the broken filename, and navigate to the proper save location.

**Comment by cfhammill** [comment]
Hmm, not sure if this is something we can address easily, but I will look in to it.

**Comment by cfhammill** [comment]
I think I'm going to close this, when the app is open in a browser this isn't an issue - hopefully rstudio has fixed this by now. If it's still a problem re-open and I'll investigate. My bet is it's choosing a most recent directory type default which may be uninitialized in the rstudio previewer.
