### ISSUE TITLE
IDEA: Initially set Shiny max threshold to max of t-stat data

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#178]
Rather than setting arbitrarily to 15, set to the max value of the stat column being displayed.

**Comment by cfhammill** [comment]
I like the idea, only down-side is then you would be unable to scale it to greater than max-t, which may be useful to have a consistent thresholds across different coefs. Leaving for now, if @jasonlerch thinks it's a good idea, I'll go ahead.

**Comment by gdevenyi** [comment]
Could alternatively set the slidebar to max?

**Comment by cfhammill** [comment]
Interestingly it looks like there is code for this already in there it just doesn't seem to be getting triggered.

**Comment by cfhammill** [comment]
Fixed it. It now sets the default lower bound to the median of the data, but a higher quantile might make more sense. Happy to take suggestions for what the automatic low threshold should be set at.

**Comment by gdevenyi** [comment]
Cool thanks!
