### ISSUE TITLE
IDEA: Allow shiny to input *FDR objects to grab thresholds (and provide threshold interface)

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#179]
It occurs to me that I'm often flipping back and forth from shiny to the console to check on what the FDR values were for a given predictor.

If i could provide those for the shiny command and it had an interface to set threshold bars using them it would considerably smooth the day-to-day use of shiny.

**Comment by cfhammill** [comment]
Implemented in dev
