### ISSUE TITLE
Update to vertexEstimateDF broke it?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#181]
```R
model_left_CT = vertexLmer(leftCT ~ type*Age + Sex + (1|subject) + (1|dataset), filtered.data, parallel = c("sge",240), mask = CCmask )
model_left_CT = vertexLmerEstimateDF(model_left_CT)
Error in eval(predvars, data, env) : object 'type' not found
```

**Comment by gdevenyi** [comment]
This might be a variable name clash... I'm using type as a column name.

Input sanitize problem?

**Comment by cfhammill** [comment]
does type exist in `filtered.data`?

**Comment by cfhammill** [comment]
vertex lmer isn't setting its data attribute. Issuing a hotfix to master now.

**Comment by cfhammill** [comment]
Should be good now.

**Comment by gdevenyi** [comment]
Fixed that error, now getting:
```
model_left_CT = vertexLmerEstimateDF(model_left_CT)
Error in `$<-.data.frame`(`*tmp*`, "RMINC_DUMMY_LHS", value = c(3.11389,  : 
  replacement has 1355 rows, data has 1358
```

**Comment by cfhammill** [comment]
We had this problem with the voxelwise version, and it's fixed there so it should be pretty trivial to fix. I'm swamped this week and gone the following so it won't get fixed for a little bit. Temporary work around, filter the NAs from your data before fitting the model.

**Comment by gdevenyi** [comment]
k, thanks.
