### ISSUE TITLE
anatFDR accepts a 'columns' argument but this produces incorrect results

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#186]
i.e.,
```
thresholds(anatFDR(fit_all, columns=c("tvalue-sexM")))
```
doesn't equal (edit: except in certain calls where it does, seemingly depending on the shape of the input and columns requested, but this isn't a simple renaming issue like the previous mincFDR 'columns' bug)
```
thresholds(anatFDR(fit_all))[,'tvalue-sexM']
```

**Comment by cfhammill** [comment]
Hmm, use of the colnames feature doesn't (currently) play well with how we do our degrees of freedom tracking. I will hack in a fix, but this might be a case where using S4/R6 objects would make a lot of sense.

**Comment by cfhammill** [comment]
I think this is fixed, care to check?
