### ISSUE TITLE
Error checking for mincFDR statType argument

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#188]
spot the error:

```
> mincFDR(buffer=..., column=..., statType='t', df=...)
Error in pi0est(p, ...) : 
  ERROR: The estimated pi0 <= 0. Check that you have valid p-values or use a different range of lambda.
```

**Comment by cfhammill** [comment]
This is (I suspect) the choking Gabe noticed when all the t-values are incredibly large (e.g. intercept term). I assume you're using `method = "qvalue"`?

**Comment by gdevenyi** [comment]
This looks familliar to https://github.com/Mouse-Imaging-Centre/RMINC/issues/95

**Comment by bcdarwin** [comment]
It's a different bug, since changing 't' to 'T' fixes it :)

**Comment by cfhammill** [comment]
This function probably needs a rewrite... I can't figure out why 'T' even works, it is not an allowed `statType`...

**Comment by cfhammill** [comment]
I think extricating the statType check in 24ef735a77dcab54de0e4a603cde24baf75b901c should have fixed this.
