### ISSUE TITLE
mincPlotSliceSeries other dimensions are broken

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#192]
Trying a dimension other than the default:

![image](https://user-images.githubusercontent.com/3001850/33328822-05f0349e-d429-11e7-8f27-f9e9c7037ba4.png)

**Comment by cfhammill** [comment]
Odd, I've used other dimensions in the past. I'll look in to it.

**Comment by bcdarwin** [comment]
I think I might have seen this before and IIRC it was a thresholding bug ... what if you put an upper threshold on the t-stats and/or set symmetric=T ?

**Comment by gdevenyi** [comment]
This was a bug with and without an upper threshold. The threshold was way above what the max value probably was.

**Comment by cfhammill** [comment]
Does this reproduce in the terminal?

**Comment by gdevenyi** [comment]
User long gone. Can no longer test. Haven't seen something like this since.
