### ISSUE TITLE
Make ShinyRMINC compatible with non-lm stats inputs.

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#193]
stats is an object generated from hanatToVolume which works fine in plot series
```R
> launch_shinyRMINC(stats, anatVol)
Converting to mincArray - might take a second or two
Error in if (keepBetas || sType[i] != "beta") { :
 missing value where TRUE/FALSE **needed**
```

**Comment by cfhammill** [comment]
As far as I'm aware hanat stats have not yet been made compatible with shinyRMINC. I'll change this to a feature request.

**Comment by gdevenyi** [comment]
Adjusting this feature request title a bit more.

We get this same bug if I load up anatomy and a minc file from disk as a "stats" image to visualize. mincPlotSliceSeries works fine though.

**Comment by cfhammill** [comment]
I guess in its present state shinyRMINC is just to visualize `mincLm` output, not a general purpose stat explorer. No reason it couldn't be, but that wasn't the initial aim as far as I'm aware. I'll probably need a mental break from what I'm working on now sometime before the holidays and will try to fix all outstanding shinyRMINC issues.

**Comment by gdevenyi** [comment]
It's just such a wonderful tool we intend to use it for so many things!

**Comment by cfhammill** [comment]
Just pushed a commit to dev that should hopefully fix this, I don't have anything lying around to test with, so give it a whirl when you get a chance.

**Comment by cfhammill** [comment]
Cleaned it up and tried it out. Single slice mode crashes but slice series works fine.
