### ISSUE TITLE
Request: subject-wise summary statistics

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#196]
vertexSummaries is helpful for producing summary statistics across vertices, however we often want the mean or sum on a subject wise basis.

Right now we vertexTable and do it ourselves, but it would be nice to avoid loading the data into memory by using the RMINC interfaces.

**Comment by cfhammill** [comment]
Hi Gabe,

I'm trying to understand the use case here. Do you want, say, mean thickness for each subject? If so then I guess the issue is that memory is limited?

in which case you could apply over the filenames like so:

```
subj_thicknesses <- sapply(filenames, function(f) mean(vertexTable(f)) )
```

which I guess is a transposed `vertexApply`.

**Comment by cfhammill** [comment]
I wrote an option into `vertexApply`, if you pass `transpose = TRUE` it will transpose your vertexTable and apply your function by subject. So you should be able to do 

```
subj_means <- vertexApply(filenames, mean, transpose = TRUE)
```

in dev.

**Comment by gdevenyi** [comment]
Yes, I want mean across subjects. This is even better, because sometimes I want to do arbitrary things. Thanks!

**Comment by cfhammill** [comment]
It's not as memory efficient as a streaming/sequential version, it still materializes the whole vertexTable, but I think in most cases vertex tables are small enough for RAM. Although maybe things are different with the highres surfaces, I haven't started using them yet.
