### ISSUE TITLE
Rgl snapshot of 3D visualizations fails without nvidia drivers

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#200]
This is an rgl problem as far as I can tell, or some quirk of our system. In my case snapshots were all black, in Darren's case they were all white.

**Comment by cfhammill** [comment]
issue 200

**Comment by gdevenyi** [comment]
Rgl falls over pretty badly for me in RMarkdown as well. But I'm not at all surprised.

This feels very much like the old plotting mess that is MATLAB and automated saving of figures where it was secretly using an OpenGL backend for everything underneath.

I had the failure when running a rmarkdown build remotely without an active X connection.

**Comment by cfhammill** [comment]
rgl can't work without X, and in theory works with rmd via a webgl conversion hook, but it's slooooow. That was part of my motivation to make the JS version. Although phantomJS is dead, but the chrome driver has gotten better at snapshotting.

**Comment by cfhammill** [comment]
I won't fix this, rbrainbrowser is functional now, any dev effort should be directed there. Feel free to use / contribute: https://github.com/cfhammill/rbrainbrowser
