### ISSUE TITLE
RMINC/1.5.0.0 vertexEstimateDF error, can't see predictor

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#203]
```R
> vs = vertexLmer(left_thickness ~ timepoint + (1|id), data = longi)
> vs=vertexLmerEstimateDF(vs)
Error in eval(predvars, data, env) : object 'timepoint' not found
```
timepoint is a regular factor in longi with two levels "0" and "2".

**Comment by cfhammill** [comment]
I suspect this won't fix it, but does it work with 1.5.1.0?

**Comment by cfhammill** [comment]
I take that back, this looks like a duplicate of #181, which got fixed between 1.5.0 and 1.5.1

**Comment by gdevenyi** [comment]
Weird, need to check which version is running.

**Comment by gdevenyi** [comment]
My bad, user wasn't loading latest version 1.5.1.0, this was fixed.

**Comment by cfhammill** [comment]
*phew*
