### ISSUE TITLE
Add left/right colour_range to obj_montage

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#219]
Often thresholds differ on the left vs right, it would be nice to be able to specify those levels separately.

For automation purposes, allowing a value of "NA" to say "don't display anything" would be helpful as well (to automate a pipeline of vertexLm -> vertexFDR -> obj_montage with minimal logic)

**Comment by cfhammill** [comment]
Fair, I think this code is going to change in the near future to use brainbrowser under the hood. I'd like things to be more compositional, like Jason's MRIcrotome.

**Comment by cfhammill** [comment]
This will be possible in rbrainbrowser
