### ISSUE TITLE
Default tests for finding minc-toolkit don't conform to how packaging works now.

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#222]
minc-toolkit no longer installs in /opt/minc, instead it installs in /opt/minc/x.y.z

**Comment by cfhammill** [comment]
yes, this is true, I really do need to fix this. Although if `mincinfo` is on your search path it will check `../lib` from where `mincinfo` is (if I remember correctly) so it should still find the toolkit.

**Comment by cfhammill** [comment]
This should be fixed by Vlad's PR.
