### ISSUE TITLE
Conda packaging?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#224]
Conda now has R available in its packaging. A RMINC conda package in conda-forge would be really nice. I think Vlad is working on minc-toolkit conda-forge packages.

**Comment by cfhammill** [comment]
My experience with anaconda has been extremely negative. It used to do something bizarre like live patching your PATH, it broke RMINC installs for people not even using anaconda's R. 

I'm not against this existing, especially if it will be a substantial hook for new users. But python's packaging story is byzantine and R's is simple, I don't want to lead R users down that path unwittingly.

**Comment by vfonov** [comment]
`conda install -c vfonov rminc `
YMMV

**Comment by cfhammill** [comment]
nice! thanks @vfonov

**Comment by gdevenyi** [comment]
Awesome, thanks @vfonov
