### ISSUE TITLE
getRMINCTestData() output directory unclear

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#228]
The example code:
```
getRMINCTestData()
# read the text file describing the dataset
gf <- read.csv("/tmp/rminctestdata/test_data_set.csv")
```
Checking ``/tmp``:
``/tmp/Rtmp7A99LX/rminctestdata.tar.gz``

**Comment by cfhammill** [comment]
Good idea, write now it returns `invisible(NULL)`, I'll have it return `invisible(extractedPath)` instead
