### ISSUE TITLE
consistency: hanat* models use "." instead of "-" to prefix predictor names

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#243]
A anatLmer model has columns such as "tvalue-age", an equivalent hanatLmer model has "tvalue.age" instead. Took us a while to figure this out as #242 didn't give us the most useful error.

**Comment by gdevenyi** [comment]
A foolish consistency is the hobgoblin of little minds.

I'd be happy with a better way to find the column names in the hanat* model object. I found that I couldn't inspect the object in rstudio unlike some other RMINC objects, and printing it resulted in the tree, rather than the model columns being displayed. Eventually found that names worked.

Of course #242 caused pain as well, since I didn't know I was misnaming the column to begin with.

**Comment by cfhammill** [comment]
I think I'll close this for now. If anyone feels strongly that we should change the naming convention we can reopen.
