### ISSUE TITLE
RMINC/1.5.2.1 hanatLmer fails to run

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#244]
Checked over all the volumes and tried an hanatLm run, that works fine, error:

```R
model = hanatLmer(~ sex + (1|mouse_id), filtered.volumes, vols)
Error in mkRespMod(fr, REML = REMLpass) : NA/NaN/Inf in 'y'
```

**Comment by cfhammill** [comment]
Want to send me an rda/rds file for this and I can have a look?

**Comment by gdevenyi** [comment]
RDS files attached. Renammed vols to myvols because there's also a column in filtered.volumes called "vols". Didn't fix the problem.

[files.zip](https://github.com/Mouse-Imaging-Centre/RMINC/files/2895364/files.zip)

**Comment by cfhammill** [comment]
Some subjects are missing volumes from "lobule 8 white matter"  "left paramedian lobule" and "left subependymal zone". Subjects 26  31  32  35  45  53  99 182.

**Comment by gdevenyi** [comment]
Cool thanks.
