### ISSUE TITLE
mincFDR fails for mincLmer models with summary_type="both"

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#246]
We wanted to examine the random effects in addition to the fixed effects so we adjusted summary_type to provide the extra data.

mincLmerEstimateDF worked, however mincFDR doesn't:
```
Error in mincFDR.mincLmer(lmermodel1, mask = statsmask) : 
  Mismatch between DF and number of columns
```

**Comment by cfhammill** [comment]
Frequentist inference of random effects eh? 

The alternative summaries weren't written with `mincLmerEstimateDF` and friends in mind unfortunately. Estimating dfs for the random effects is something I don't know how to do off hand, so I'd recommend splitting the random effects out from the matrix, and renaming the fixef columns such that it looks like a normal mincLmer output. Then estimateDF and FDR should work. There may be additional massaging needed, but I hope not.

To do inference on the random effects, you can take the t-stats, and do mixture-modelling based FDR on those directly (don't go through p). We might have some code lying around to do mixture of gaussians, I'm also fond of the `fdrtool` package which uses modified grenander estimators for modelling the alternative distribution.
