### ISSUE TITLE
Feature request: Allow plotting tools to determine begin/end from bounding box of mask

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#248]
Currently to quickly tune begin and end for mincplotliceseries I use ``mincbbox -minccrop`` which gives me start and ending limits. It would be nice if the plot tools could do this natively.

There's probably an R-way to do this by loading the mask and such but I still don't think that way...

**Comment by jasonlerch** [comment]
Good idea - but also more sensible for MRIcrotome if being incorporated with visualization.

________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.
