### ISSUE TITLE
mincPlotSlice series legend overlaps with colourbar

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#249]
![image](https://user-images.githubusercontent.com/3001850/51273974-fb677f00-199b-11e9-832a-55e39aa37a4c.png)

**Comment by jasonlerch** [comment]
use MRIcrotome - it is unlikely for us to put effort into fixing mincPlotSlice and friends.

https://rawgit.com/Mouse-Imaging-Centre/MRIcrotome/master/vignettes/figures.html

https://github.com/Mouse-Imaging-Centre/MRIcrotome



________________________________

This e-mail may contain confidential, personal and/or health information(information which may be subject to legal restrictions on use, retention and/or disclosure) for the sole use of the intended recipient. Any review or distribution by anyone other than the person for whom it was originally intended is strictly prohibited. If you have received this e-mail in error, please contact the sender and delete all copies.

**Comment by gdevenyi** [comment]
Okay, will transition to making figures this way. Thanks.

**Comment by gdevenyi** [comment]
Fixed this slightly following the advice from https://github.com/Mouse-Imaging-Centre/MRIcrotome/issues/8

**Comment by cfhammill** [comment]
Closing in anticipation of slowly deprecating the old viz code.
