### ISSUE TITLE
anatGetAll documentation should specify defs=NULL works and what it does

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#259]
If I don't have a defs file, anatGetAll should just use the label number from the atlas file.

**Comment by cfhammill** [comment]
It does (or should). Does this not work anymore? 

https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_anatomy.R#L256

**Comment by gdevenyi** [comment]
Ah. So it does.

But it defaults to a environment variable and bails out on error if unspecified.

Also, the docs don't say NULL is allowed. :)

**Comment by cfhammill** [comment]
Oops, my fault, `Sys.getenv` on fail returns an empty string instead of NULL, so on other systems the default gets initialized incorrectly. I'll fix and doc, thanks for the spot.

**Comment by cfhammill** [comment]
Fixed.
