### ISSUE TITLE
What version of R is supported for RMINC?

### ISSUE THREAD

**Issue by Dorky-Lever** [Mouse-Imaging-Centre/RMINC#263]
Hi Everyone,

May I ask what version of R is supported for RMINC? 
I can't find any details about this in the documentation (all I know is that RMINC requires R > 3.1.0). 

Kind Regards,
Kyle Drover

**Comment by gdevenyi** [comment]
https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/DESCRIPTION

Lists R>3.2.0

I've used 3.4.0 to 3.5.1 successfully.

**Comment by cfhammill** [comment]
Builds on our travis CI with tests passing with 3.6.0 too (theres a doc warning so the build lists as failed, maybe one day I will have time to fix this...)
