### ISSUE TITLE
mincTable or equivalent to vertexTable?

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#271]
We're beginning to experiment with multivariate methods which require all the data at once. With CIVET with can use vertexTable but I can't readily find an equivalent for MINC files. Does this exist?

Otherwise, I guess I can do an apply wrapper on mincGetVolume.

**Comment by cfhammill** [comment]
Doesn't exist yet. I doubt we can do much better than `sapply` over `mincGetVolume` or similar. The outer loop being a touch slow would be irrelevant performance-wise. 

I worry though that you will need to down-sample to get a modestly sized experiment in to RAM. R's vectors are uncompressed doubles so memory adds up quick. This is one of the reasons I haven't added something like this yet. I've considered implementing file-backed matrices but haven't had sufficient impetus. 

Standard practice in machine learning these days is to do batched training where you never have the full data set in memory anyway. Depending on what you're working on that may be a potential solution.

**Comment by gdevenyi** [comment]
> R's vectors are uncompressed doubles so memory adds up quick. 
Indeed it does, stuff blows up quick when I try to use it :) Thankfully I have some high ram machines around now.

My implementation, for posterity. I think this will cause me pain if I ever want to get back into image space. But maybe not. 
```
mask = mincGetVolume("../../derivatives/statsmask.mnc")
mysubset$reljacdata = t(sapply(mysubset$reljacdata, mincGetVolume)[mask > 0,])
```

**Comment by cfhammill** [comment]
you can make it a bit more memory efficient by doing:

```r
t(sapply(mysubset$reljacdata, function(f) mincGetVolume(f)[mask > 0,])
```

but otherwise looks like exactly what I would do. Getting back to image space is actually not so bad.

```r
# For one vector of output
outvol <- mask
outvol[mask < 0.5] <- 0
outvol[mask >= 0.5] <- masked_result
```
It will actually keep the likeVolume from the mask file so it will write out and work with `mincArray` cleanly.

**Comment by gdevenyi** [comment]
Cheers! That's what I was thinking. Thanks for the optimization. Now we can avoid Matlab(and nifti) for pls code.

I'll leave this open for documentation. Maybe I'll write a function.

**Comment by gdevenyi** [comment]
Turns out the memory efficient sapply doesn't work.. :)

```
 mysubset$reljacdata = t(sapply(mysubset$reljacdata, function(f) mincGetVolume(f)[mask > 0]))
Error in `$<-.data.frame`(`*tmp*`, reljacdata, value = list()) : 
  replacement has 1 row, data has 72
```

I don't quite get why though :)

**Comment by cfhammill** [comment]
Looks like you're updating `mysubset$reljacdata` inplace. Is it possible you ran the working inefficient version and obliterated the filename column? I'd try recreating `mysubset` and running the `sapply` to separate variable (not straight in to the data.frame either) to see what gets produced.

**Comment by cfhammill** [comment]
Addendum: if `sapply` failed to simplify the results to `matrix` and produced a list, `t` will turn a list into a 1 row `matrix` producing the error you saw above. Isn't R wonderful ;)

**Comment by gdevenyi** [comment]
Definitely option #2, I'll see if I can sort that.

**Comment by cfhammill** [comment]
Odd, not sure what fouled up the simplification.

**Comment by cfhammill** [comment]
Any word on what happened? I've used the above code successfully recently. Also turns out there's an unexported function for this in RMINC you can access with `r RMINC:::minc.get.volumes`, although it doesn't support masking. I'm going to extend this adding optional file backing for the matrix in case it goes out of memory and get it in develop today.

**Comment by gdevenyi** [comment]
Ah, I see I made a typo: code was:
```
t(sapply(mysubset$reljacdata, function(f) mincGetVolume(f)[mask > 0]))
```
but should be:
```
t(sapply(mysubset$reljac, function(f) mincGetVolume(f)[mask > 0]))
```

I was pointing at the wrong column for getting the filenames

**Comment by cfhammill** [comment]
I have a working version in https://github.com/Mouse-Imaging-Centre/RMINC/tree/mincTable-file-backing, feel free to kick the tires. This will probably make it into master on Monday.
