### ISSUE TITLE
Accept test data location when building package

### ISSUE THREAD

**Issue by bcdarwin** [Mouse-Imaging-Centre/RMINC#272]

**Comment by cfhammill** [comment]
I modified `runRMINCTestbed` to accept a `datadir` argument  a while ago. I think I could probably put this together by adding a `RMINC_DATA_DIR` environment variable lookup in `RMINC.R`, promoting it to an R `option` then using `getOption` in `runRMINCTestbed`.

**Comment by cfhammill** [comment]
I have an experimental patch implementing this. The only potential issue I see is that RMINC edits the unpacked files inplace [swapping stub full paths for wherever the test data tarball unpacks]. I assume nix doesn't want you modifying other parts of the store, so this may be impossible.

**Comment by bcdarwin** [comment]
That's not bad because the Nix expression can just copy the data from the store into the build directory.

**Comment by cfhammill** [comment]
If you can experiment on develop you should be good to go - if this needs to make it to master first I can cut a small release.

**Comment by bcdarwin** [comment]
All I need is a tag or even a commit hash :)

**Comment by bcdarwin** [comment]
As we discovered, it looks like `dataPath` isn't propagated correctly into individual tests such as `test_anatAnova`, which triggers data downloading.

**Comment by cfhammill** [comment]
This appears to be a false alarm, specific to the nix build process, where an absolute path for the data directory needs to be provided.
