### ISSUE TITLE
Revamp travis builds

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#273]
Can't figure out where the warnings are coming from. I think it's still the new convergence check in lme4, but I don't know for sure.

**Comment by cfhammill** [comment]
In the process of solving the original issue I noticed that we can upgrade our builds from ubuntu trusty to xenial. This has involved some tweaking of the build. Triggered repairing the mac build, which was failing due to missing libz. I started using binary installs for tidyverse which I'm optimistic will cut linux build times down dramatically.

**Comment by cfhammill** [comment]
This may be a suboptimal allocation of time if we end up using @bcdarwin's nix builds in the future, but it will be nice to have working CI builds until then.

**Comment by cfhammill** [comment]
Addendum to the switch to binary builds, this may not be the right choice, not sure how far behind CRAN the deb archives stay. Might be prudent to test with the newest tidyverse packages. This would be solved with nix+cachix anyway.

**Comment by gdevenyi** [comment]
These stay very up to date, https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5

**Comment by cfhammill** [comment]
So they do, thanks @gdevenyi!

**Comment by cfhammill** [comment]
Linux builds up an running, mac still struggling to link zlib. 

Test warnings on linux (https://travis-ci.org/cfhammill/RMINC/jobs/655449981):

- [ ] `untar(decompress = )` deprecation. Easy fix in minc_interface.R `getRMINCTestdata` 
- [ ] `filter_`, `arrange_`, `mutate_`, `tibble_` . These were deprecated long ago, but have now been
       upgraded to a warning.  Same as #157. I don't know whether to use `!!`, `.data`, or the new
      "curly-curly" syntax `{{}}` to fix this. Probably will use `!!` with `as.symbol`.
- [ ] convergence warnings from `lmer`, will probably need to trap these.
- [ ] ties in wilcoxon  tests

**Comment by cfhammill** [comment]
Mac builds are working now. Down to one residual NSE error and the other two above

**Comment by cfhammill** [comment]
Builds are now squeaky clean! Other than travis continuing to hide some output. I opened an issue on the forum (encouraged over github issues now). https://travis-ci.community/t/r-cmd-check-log-lines-hidden/7399

Apart from a red-herring response nothing yet. I trust it will resolve, and is mostly ignorable - if we see failures we may have to run check locally to get full output.
