### ISSUE TITLE
Allow forcing of libminc build

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#283]
The combination of conda's R environment + minc-toolkit built elsewhere simply won't play well, partially because of https://github.com/BIC-MNI/minc-toolkit-v2/issues/45 but also other conflicting libraries.

The built-in libminc build inside RMINC does seem to work.

I can't find a way to override the detection of the existing minc-toolkit install, other than to wholesale rename /opt/minc so the configure misses it and then rename it back afterwards.

Is there another option?

**Comment by cfhammill** [comment]
I've only ever had problems with conda, I could usually get RMINC to build properly by purging any reference to anaconda from `$PATH`, this way it doesn't pick up an inappropriate `h5cc`, which broke the build. From there it's been fine to use once the PATH has been restored. I suspect you're running in to this issue.

**Comment by gdevenyi** [comment]
not in this case, I don't even have an HDF5 in my conda.

It either fails on can't find HDF5 libraries (because the configure tries to use h5cc to get configs, but https://github.com/BIC-MNI/minc-toolkit-v2/issues/45 means it can't find it). Or, if I hard-code -lhdf5 into the linker settings, then I get a glibc version mismatch error. Possibly due to using the 18.04 minc-toolkit with 20.04, however minc-toolkit itself works.

I see I did make 19.04 packages, I should test those I guess instead.

**Comment by cfhammill** [comment]
Can you post the full build logs?

**Comment by gdevenyi** [comment]
The configure fails at the -lminc2 test (after hackery to force -lhdf5 as noted above)
```
configure:4428: checking for mifree_name in -lminc2
configure:4453: /home/localadmin/.conda/envs/r-environment/bin/x86_64-conda_cos6-linux-gnu-cc -o conftest -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/localadmin/.conda/envs/r-environment/include  -DNDEB
UG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/localadmin/.conda/envs/r-environment/include -I/opt/minc/1.9.17/include   -L/opt/minc/1.9.17/lib -Wl,-rpath,/opt/minc/1.9.17/lib  conftest.c -lminc2 -lhdf5 -lm -ldl   >&5
/home/localadmin/.conda/envs/r-environment/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /opt/minc/1.9.17/lib/libminc2.so: undefined reference to `log@GLIBC_2.29'
/home/localadmin/.conda/envs/r-environment/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /opt/minc/1.9.17/lib/libminc2.so: undefined reference to `memcpy@GLIBC_2.14'
/home/localadmin/.conda/envs/r-environment/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.5.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /opt/minc/1.9.17/lib/libhdf5.so: undefined reference to `pow@GLIBC_2.29'
collect2: error: ld returned 1 exit status
```

I suspect this is some sort of static vs shared situation?

**Comment by gdevenyi** [comment]
Looks like if I unset a bunch of the Conda build environment things (CC, LD etc) I can get configure to pass, will test whether than makes a functioning RMINC at the end...

**Comment by gdevenyi** [comment]
Unsetting CC is enough for the configure to pass unmodified and for RMINC to build against the local minc-toolkit and tests to run successfully.

**Comment by cfhammill** [comment]
that makes sense, glad the problem is resolved.

**Comment by gdevenyi** [comment]
Its weird that it sill successfully uses the CXX of conda, as well as the rest of the toolchain. Its just the CC invoked during the test that breaks things.
