### ISSUE TITLE
Installation of package 'Matrix' had non-zero exit status

### ISSUE THREAD

**Issue by rwickens** [Mouse-Imaging-Centre/RMINC#285]
Hello, 
Got the attached error when downloading RMINC from GitHub: 

![image](https://user-images.githubusercontent.com/24905802/82761177-b68cfd00-9dc6-11ea-9208-15a173de8310.png)

By the way, I'm working from a VM: https://github.com/CobraLab/MINC-VM. @gdevenyi 

Any help is appreciated. 
Best,
Rebekah

**Comment by gdevenyi** [comment]
1) Not a bug in RMINC
2) RMINC is already in MINC-VM.

**Comment by gdevenyi** [comment]
![image](https://user-images.githubusercontent.com/3001850/82761424-775fab80-9dc8-11ea-95ce-ab96b4839fea.png)

**Comment by rwickens** [comment]
![image](https://user-images.githubusercontent.com/24905802/82761660-28b31100-9dca-11ea-8627-f496b881f302.png)

**Comment by gdevenyi** [comment]
All programs must be opened from the terminal, this is still not an RMINC issue.
![image](https://user-images.githubusercontent.com/3001850/82761731-a7a84980-9dca-11ea-8861-34b1b76b1616.png)

**Comment by rwickens** [comment]
Ok, all seems to be well, then. Thanks.
