### ISSUE TITLE
Move test data to a release attachment

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#313]
wiki.mouseimaging.ca is regularly having issues, having the data somewhere might be a good idea

**Comment by bcdarwin** [comment]
See https://github.com/Mouse-Imaging-Centre/RMINC-test-data.

PR #312 modifies the tests to pull from there when it's merged.

**Comment by gdevenyi** [comment]
Cool, missed that. Thanks.
