### ISSUE TITLE
Downdated VtV is not positive definite error causes mincLmer to crash without output

### ISSUE THREAD

**Issue by vfonov** [Mouse-Imaging-Centre/RMINC#35]
Running simple voxelwise mixed effect fitting:

model<-mincLmer(log_det~cohort+(1|subj),data=dbm,mask='model_nl_c/avg.016_mask_lr.mnc',parallel=c("snowfall", 4)) 

works for a while and then prints:

Error in checkForRemoteErrors(val) : 
  4 nodes produced errors; first error: Downdated VtV is not positive definite

and produces no output

**Comment by cfhammill** [comment]
This appears to be a known issue in lme4 https://github.com/lme4/lme4/issues/173 for when parameters are scaled poorly. Ben Bolker recommends scaling continuous predictors, but I'm assuming cohort is a factor. Do you have any sense of how many voxels this failed on? 

Irrespective of bug source it is probably worth handling error cases more elegantly, e.g. returning NAs, returning a list of failed voxels to be run by hand etc. - I will investigate.

**Comment by cfhammill** [comment]
I have added a "safely" boolean argument to `mincLmer`, this will downgrade warnings to errors in the lmer optimization code returning NA for that voxel.
