### ISSUE TITLE
BUG: RMINC fails with latest lmerTest (2.0-20)

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#39]
There was a code re-factoring in 2.0-20 which renamed some internal functions that RMINC is using from lmerTest. Version 2.0-11 works fine.

Particularly ``rhoInit``though there may be others, that was the first bug I ran into.

**Comment by jasonlerch** [comment]
I guess that's the price for using internal functions. Will look into it, but dread the idea of needing branching within RMINC depending on lmerTest versions, so will likely wait a bit and then switch to requiring the new version.

**Comment by gdevenyi** [comment]
Maybe do this for the next release, since looks like a lot of big changes coming?

**Comment by gdevenyi** [comment]
Just a followup, we're now at lmerTest 2.0-29

**Comment by jasonlerch** [comment]
Still on our todo list. Hopefully we’ll get to it soon.

**Comment by cfhammill** [comment]
This is fixed in the development branch, should be brought in to master soon

**Comment by gdevenyi** [comment]
Fixed in devel
