### ISSUE TITLE
anatLm allows for only up to 2 terms

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#42]
E.g, the following works:

anatLm(~ Genotype + Sex, data_frame, volume_data)

but this doesn't work:

anatLm(~ Genotype + Sex + Age, data_frame, volume_data)

The error message you'll get will be as follows:

Error in parse(text = rCommand) : <text>:1:14: unexpected '+'
1: term <- data$+

**Comment by gdevenyi** [comment]
Now anatLm's with longer formulas report:
```
Warning message:
In if (!as.character(formula[[2]][[nTerm]]) %in% names(data)) { :
the condition has length > 1 and only the first element will be used
```

Can't tell immediately if this is a bug or intended?

**Comment by jasonlerch** [comment]
Can you check, for some random ROI, whether the result of summary(lm()) and anatLm are the same? That’s the surest way to ascertain whether it is a serious bug or just an annoying message we’ll have to look into.

Thanks!

Jason

**Comment by gdevenyi** [comment]
Yup, they're the same, looks like it's just an annoying message.

**Comment by cfhammill** [comment]
looks like we need to wrap the condition in `all()`  to fix this. Right now, as it's saying in the warning, only the first rhs formula term is being tested. I will make this fix soon.
