### ISSUE TITLE
Feature Request: "mask" for vertexLm and related vertex operations

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#47]
CIVET (for example) has a region of "known bad" measures which I would never interpret as being significant in a t-stat map.

Right now what I do is zero out the t-stat file RMINC creates with a mask (flat text file) file of "0" and "1" the length of the vertex file using bc.

It might be useful to allow for masking of vertexLm (and related functions) with such a mask file, and fill the masked region with either 0 (preferred) or NA (probably breaks some viewing software).

**Comment by gdevenyi** [comment]
Looks like this is half-implemented in vertexFDR which states:
```
    mask: Either a filename or a numeric vector representing a mask
          only values inside the mask will be used to compute the
          threshold.
```

**Comment by gdevenyi** [comment]
Looks like this works:

```
CCmask = read.table("/opt/quarantine/resources/CIVET-CC-mask.txt")
vertexFDR = function (buffer, method = "FDR", mask = NULL) 
{
  mincFDR.mincMultiDim(buffer, columns = NULL, mask = mask, 
                       df = NULL, method = method)
}

> vertexFDR(vertexlm_result, mask = CCmask)
```

**Comment by cfhammill** [comment]
Hmm, looks like mask was hard set to NULL in `vertexFDR`. I've changed this in develop to honour your choice. 

Thanks Gabe

**Comment by gdevenyi** [comment]
Fixed.
