### ISSUE TITLE
Speed up mincFDR

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#55]
Investigate slowness of mincFDR

**Comment by jasonlerch** [comment]
The FDR implementation for the lmer functions is much faster. That style of FDR by inheritance is likely the best solution vs all the if else clauses in the current implementation.

**Comment by cfhammill** [comment]
Hmm, running profvis on `mincFDR` shows that the bulk of the time is spent in p.adjust (~ 60%). With the remaining time in one of the distribution functions (pt, pf). These are the same functions used in `mincFDR.mincLmer`. @jasonlerch you mentioned that the poor performance is stochastic? I noticed in a couple of rounds of profvis `mincFDR` would hang indefinitely.

**Comment by cfhammill** [comment]
Profiling reveals no obvious fat to trim. Closing until we notice it being problematic
