### ISSUE TITLE
Feature Request: anatLmer like mincLmer

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#58]
Similar to #37 we're getting more and more longitudinal data which we would love to use the RMINC tools directly to analyze.

For now I'm doing ugly ugly for loops (because I'm bad at R) to loop over volumes from MAGeT to run Lmer

**Comment by cfhammill** [comment]
Written and will likely be ready for the next release. How many labels does your CIVET data have? The version I wrote is slow relative to mincLmer, it performs a full model fit, as opposed to our lightening fast refitting code. This also allows anatLmer to estimate the degrees of freedom internally operating on the assumption that the number of labels is relatively small.

**Comment by jasonlerch** [comment]
I think that’s a bad choice – the implementation should be the same as mincLmer. Both for consistency, but mainly since the anat family of functions are great for using whenever one has an array in memory of whatever size (i.e. could be quite large).

**Comment by gdevenyi** [comment]
This is MAGeT data with at the moment is maximum 63 volumes, and for CIVET "mean" bulk area it would be 78.

**Comment by gdevenyi** [comment]
This would also be for maget output from pydpiper of course.

**Comment by cfhammill** [comment]
@jasonlerch ok, I had implemented it with the mincLmerOptimizeAndExtract at first, so I will roll back to that

**Comment by cfhammill** [comment]
Added parallelization, should be ready for release in the next week or so.
