### ISSUE TITLE
anatLm fails to run on integer data

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#60]
If I happen to have data for anatLm from 1x1x1 isotropic labels, all my outputs are integer, and R read.csv loads the data as int.

When I run anatLm on this, I get the following error:

``` R
Error in anatLm(~sex * group + age_MRI + tbv, filtered.volumes, filtered.volumes$maget_morpho5) : 
REAL() can only be applied to a 'numeric', not a 'integer'
```

Fixed by explicitly specifying numeric in read.csv column specifications, but it would be nice if anatLm transformed this type.

**Comment by jasonlerch** [comment]
Thanks for catching that - will fix for the next release.

**Comment by gdevenyi** [comment]
Fixed I think?
