### ISSUE TITLE
Proposal: Reorganize /R 

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#62]
Currently the source file organization in /R is less descriptive than it could be, I'd like to reorganize it as follows:

| File | Contents |
| --- | --- |
| minc_compute.R | Move all functions for computing summaries and statistics (except mincLmer) from minc_interface to their own file, including the sequential mincApply family. |
| minc_anatomy.R | rename structure_funcs.R |
| minc_vis2D.R | rename visualizations.R |
| minc_vis3D.R | rename obj_functions.R |
| minc_parallel.R | move all parallel functions from minc_interface.R to their own file |
| minc_lmer.R | move mincLmer related code to its own file |
| minc_shiny.R | rename shinyRMINC |
| minc_misc.R | merge extra code spread across fast_qvalue.R, minc_support.R, and volumetric.R to their one miscellaneous functions file. |
| civet.R | left as is (or maybe rename as minc_cortical.R to match naming convention) |
| RMINC.R | left as is |
| RcppExports.R | left as is (automatically generated by RCPP) |

Any objections?

**Comment by mcvaneede** [comment]
I have no objections. The proposed naming scheme looks very clear.

**Comment by cfhammill** [comment]
Thanks Matthijs, I'll go ahead with the changes if no one else chimes in.
