### ISSUE TITLE
remove packageData

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#66]
This directory is quite large and does not appear to be used. It was last touched 7 years ago during the merge of mincIO, can it be deleted?

**Comment by mcvaneede** [comment]
I think so. This was used to generate the original documentation file, wasn't it? And a better option is probably to have this kind of data on our side (wiki or repo) such that it can be downloaded.

**Comment by cfhammill** [comment]
Ahh I had forgotten it was used in VBMstats. I have two thoughts for how to proceed, we could keep the data in the package, but if we do we should probably make it so that the documentation can be built and tested automatically (we could fake the results for slow running code to make it run in a reasonable amount of time if necessary). Or we could put a note in the documentation on where to find the data elsewhere, this may make CRAN slightly happier.

**Comment by mcvaneede** [comment]
My vote goes to option 2: moving the data elsewhere which makes the repository a fair bit smaller and it makes CRAN happier!
