### ISSUE TITLE
C-code cannot handle integer data

### ISSUE THREAD

**Issue by yohanyee** [Mouse-Imaging-Centre/RMINC#68]
```mincApply(files, quote(which.max(x)), mask=mask)``` fails and returns the error: ```REAL() can only be applied to a 'numeric', not a 'integer'```. I suspect this is because which.max() returns an integer rather than numeric object. This is fixed by wrapping the function with as.numeric(): ```mincApply(files, quote(as.numeric(which.max(x))), mask=mask)```

**Comment by cfhammill** [comment]
Hi Yohan,

In the development branch of RMINC there is a newer apply function `mincApplyRCPP` that can handle more return types than the numeric (double) return expected by `mincApply`'s c-code under the hood. For now your work-around shouldn't cause problems.

**Comment by cfhammill** [comment]
C-code would be hard to change in order to accommodate this and the work-around is simple enough. Closing for now.
