### ISSUE TITLE
vertexApply doesn't work like apply

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#70]
When I use "apply" in R, all I have to do is input a function name, I expected the same in vertexApply, but instead the help says ``quote(mean(x))``.

**Comment by cfhammill** [comment]
Hi Gabe, 

I believe this was done for consistency with the `mincApply` family. I've recently written a newer member of the family `mincApplyRCPP` that behaves more like the standard R applies, so it may make sense to migrate `vertexApply` up to the standard interface.

In the mean time, the code for `vertexApply` is relatively short:

```
vertexApply <- 
  function (filenames, function.string) 
   {
     vertexData = vertexTable(filenames)
     function.string = gsub("(x)", "", function.string, fixed = TRUE)
     results <- t(apply(vertexData, 1, function.string[1]))
     attr(results, "likeFile") <- filenames[1]
     gcout <- gc()
     return(results)
  }
```

you could write your own like:

```
vertexApplyR <-
  function(filenames, fun, ...){
    apply_fun <- match.fun(fun)
    vertexData <- vertexTable(filenames)
    results <- t(apply(vertexData, 1, fun, ...))
    attr(results, "likeFile") <- filenames[1]
    return(results)
}
```

**Comment by gdevenyi** [comment]
Fixed with new apply function.
