### ISSUE TITLE
Feature Request: Document Dependencies

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#72]
I build and install RMINC in a quarantine so I don't use the standard install.packages functionality, this means I need to install my dependencies manually as well, it would be great if that list were somewhere in the documentation.

**Comment by cfhammill** [comment]
Hi Gabe,

There is a dependency list in the package DESCRIPTION file. All packages listed in Depends, Imports, and Suggests dependencies.

**Comment by gdevenyi** [comment]
Cheers, that's what I was looking for.
