### ISSUE TITLE
mincPlotSliceSeries does not adjust colour scale to given range

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#75]
I created a file (based on some of Rylan's data) which has discrete values (11.5 to 17.5 in steps of 0.5). Plotting this data using mincPlotSliceSeries does not produce the correct colours for the areas in the plots:

(the example can only be run at MICe)
```
nlin_file <- mincGetVolume("/hpf/largeprojects/MICe/matthijs/2016-05-RMINC-colours/nlin-3.mnc")
test_colours_file <- mincGetVolume("/hpf/largeprojects/MICe/matthijs/2016-05-RMINC-colours/file_with_values_11.5_to_17.5.mnc")

mincPlotSliceSeries(mincArray(nlin_file), mincArray(test_colours_file), anatLow=700, anatHigh=1400,low=11.3, high=12, begin=60, end=-90, legend="Testing colours", col = rainbow(255))
# or
mincPlotSliceSeries(mincArray(nlin_file), mincArray(test_colours_file), anatLow=700, anatHigh=1400,low=11.3, high=12, begin=60, end=-90, legend="Testing colours")
```

Most values in the test file have values that are larger than 12, so the overlay should be almost completely coloured by the high end range of the colour bar

**Comment by cfhammill** [comment]
Good catch, looks like there was a scaling issue in the code, the slice was getting scaled and centred and then scaled again against its original max which pushed all the values down. I also just noticed that rainbow is a ring scale, it starts and ends red, which is probably not a good property for colour scales of this type.
