### ISSUE TITLE
Requested improvements to object_montage

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#76]
object_montage has awesome potential for creating figures as part of a complete processing pipeline written entirely in RMINC.

I had written a script that drives ray_trace (see attached) which takes RMINC outputs and produces a standard CIVET image. I'd love to see object_montage have the ability to produce something a bit more like my script.

``` sh
#!/bin/bash
#USAGE
#create_civet_image.sh left_average.obj left_statmap left_column left_FDR right_average.obj right_statmap right_column right_FDR output.png

#Automatically generates a standardized view of a brain, using stats files for left and right hemispheres (from RMINC)
#Colourizes objects using stats files, ray traces standard views and them merges them together

```

![ct-linear](https://cloud.githubusercontent.com/assets/3001850/15157648/8c259d02-16ba-11e6-9d2b-59610f5cef38.jpg)

**Comment by jasonlerch** [comment]
Have you tried the rgl based direct visualization in RMINC? Should be able to do do the same for you.

Jason

On May 10, 2016, at 2:22 PM, Gabriel A. Devenyi <notifications@github.com<mailto:notifications@github.com>> wrote:


object_montage has awesome potential for creating figures as part of a complete processing pipeline written entirely in RMINC.

I had written a script that drives ray_trace (see attached) which takes RMINC outputs and produces a standard CIVET image. I'd love to see object_montage have the ability to produce something a bit more like my script.

#!/bin/bash
#USAGE
#create_civet_image.sh left_average.obj left_statmap left_column left_FDR right_average.obj right_statmap right_column right_FDR output.png

#Automatically generates a standardized view of a brain, using stats files for left and right hemispheres (from RMINC)
#Colourizes objects using stats files, ray traces standard views and them merges them together


[ct-linear]<https://cloud.githubusercontent.com/assets/3001850/15157648/8c259d02-16ba-11e6-9d2b-59610f5cef38.jpg>

**Comment by cfhammill** [comment]
Hi Gabe,

Development of the 3D visualizations has been on the back-burner lately, still very much a work in progress. I will (when I have time) work on improving them, things that are on the to-do list are symmetric-scale colour maps like in `mincPlotSliceSeries` and cleaning/empowering the API. The original viewpoints for obj_montage were supposed to look similar to the top two views in your figure although in some objs they are flipped and I haven't had a chance to figure out why or fix them.

**Comment by gdevenyi** [comment]
Thanks, I'll dig in and see if I can replicate my script with the direct plot call.

I'll keep an eye out for the two colour maps :-)
