### ISSUE TITLE
mincLMER causes segfaults

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/RMINC#79]
Here is code I ran approximately a 6 months ago and it worked fine. Now, it results in segmentation faults.

df=read.csv("/hpf/largeprojects/MICe/dfernandes/lqiu_long/all_relative_jacobians/files.csv")
df$files=as.character(df$files)
mask="/hpf/largeprojects/MICe/dfernandes/lqiu_long/test_p65dc2/mask/mask_dimorder_eroded.mnc"
vslmer=mincLmer(files~sex*age+(1|ID), data=df, mask=mask)

Result
 *** caught segfault ***
address 0x7ffcf0048eb8, cause 'memory not mapped'

Traceback:
 1: .Call("RMINC_rcpp_minc_apply", filenames, use_mask = use_mask,     mask = mask, mask_lower_val = minmask, mask_upper_val = maxmask,     value_for_mask = masked_value, filter_masked = filter_masked,     slab_sizes = slab_sizes, return_indices = return_indices,     fun = apply_fun, args = args, PACKAGE = "RMINC")
 2: mincApplyRCPP(lmod$fr[, 1], optimizer_fun, mincLmerList = mincLmerList,     mask = mask, slab_sizes = slab_dims)
 3: mincLmer(files ~ sex * age + (1 | ID), data = df, mask = mask)

**Comment by cfhammill** [comment]
Elizabeth caught this error too, I'm investigating now.

**Comment by cfhammill** [comment]
Issue was poor memory management in mincApplyRCPP, bug fix involved changing underlying c++ code and interaction with downstream code (e.g. mincLmer). The bug is now fixed in master.
