### ISSUE TITLE
anatGetAll won't actually tell you about labels in the input that are not in the atlas

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#81]
Because of this:

https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_anatomy.R#L62

Any labels for which values were found, but did not appear in the definitions, are thrown out here. Most likely this situation indicates a real issue, so should be reported.

**Comment by cfhammill** [comment]
This issue is addressed in anatGetAll2 coming shortly
