### ISSUE TITLE
Is 0 (zero) a proper default return for a missing value in anatGetAll?

### ISSUE THREAD

**Issue by mcvaneede** [Mouse-Imaging-Centre/RMINC#83]
Here:
https://github.com/Mouse-Imaging-Centre/RMINC/blob/master/R/minc_anatomy.R#L223

When we are calculating the size of a structure, returning zero is fine, but when we ask for sums or mean for instance, zero might not be the best default.

**Comment by gdevenyi** [comment]
So I would guess the alternative is an NA, the question then becomes, can everything downstream handle NAs?
