### ISSUE TITLE
Fix your links to the wiki

### ISSUE THREAD

**Issue by psteadman** [Mouse-Imaging-Centre/RMINC#84]
They point to phenogenomics when it should be mouseimaging

**Comment by cfhammill** [comment]
Where is this in the code? Grepping for phenogenomics in the R directory turns up nothing.

**Comment by psteadman** [comment]
Hey its in your README file on the master and develop branches at least on github

**Comment by cfhammill** [comment]
ok, great, thanks for spotting that!

**Comment by psteadman** [comment]
No problem Chris :)
