### ISSUE TITLE
Feature request: R-value from vertexLm

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#86]
Would allow MACACC using vertexLm

**Comment by cfhammill** [comment]
Hi Gabe,

I don't think returning R from vertexLm will give you the answer you're looking for. Jason can correct me if I'm wrong, but you would need to calculate the pairwise correlations between each row in your vertex table, as far as I know there is no way to compute this from the linear model results. For voxel data we have `mincCorrelation`.  For vertex data you can probably assemble the vertices into a table and run R's `cor` function:

```
system.time(cor(matrix(runif(100000 * 500), ncol = 500)))
   user  system elapsed 
 37.462   0.360  37.846 
```

 A toy example of 500 brains of 100,000 vertices ran in 38 seconds on my machine. Add the overhead of reading the files in and it might take a couple of minutes, but not excessively long.

**Comment by gdevenyi** [comment]
Right, sorry, I mean seeded MACCAC, so I copy the (thickness, say) from a vertex into the dataframe to use a predictor, then a run a standard lm.

**Comment by cfhammill** [comment]
Sorry Gabe, still not quite understanding the feature request. Could you send me an email with more details?

**Comment by gdevenyi** [comment]
Nevermind, seems the original paper only ever uses R^2, never R to present the results. Sorry for the noise.
