### ISSUE TITLE
mincLmer returns masked vector

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/RMINC#87]
mincLmer returns column vectors that are masked. 
However, following the documentation, mincFDR fails because the first thing it tries to do is subset the mincLmer return with a mask.

**Comment by jasonlerch** [comment]
Getting bitten by this bug as well. Should be easy to fix; in the meantime, workaround:

vs <- mincLmer(blah ~ blah + (1|blah))
mask <- mincGetVolume("mask.mnc")
m2 <- mask
m2[mask>0.5] <- vs[,"tvalue-blah"]
