### ISSUE TITLE
mincLmer returns vector of 0s

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/RMINC#88]
df=read.csv("/hpf/largeprojects/MICe/dfernandes/lqiu_long/growth_rates2/growth_rates_relative_det.csv")

vs=mincLmer(files~sex*age+(1|ID),df,mask="/hpf/largeprojects/MICe/dfernandes/lqiu_long/test_p65dc2/mask/mask_dimorder.mnc")

columns "tvalue-sexM" "tvalue-age" "tvalue-sexM:age" are all 0

-Darren

**Comment by cfhammill** [comment]
I traced this to diag being referenced incorrectly, added and import for Matrix::diag, should be fixed now.
