### ISSUE TITLE
repeated runs of mincLmer in same directory fail "Registry is not empty"

### ISSUE THREAD

**Issue by jasonlerch** [Mouse-Imaging-Centre/RMINC#89]
Message:

```
Error in batchMap(registry, mcMincApply, mask = mask_files, more.args = mincApplyArguments) : 
  Registry is not empty!
```

I suspect there is some missing clean-up code upon mincLmer completion

**Comment by jasonlerch** [comment]
Should have added that 
`rm -rf pMincMask* qMincApply_registry/`

after each mincLmer call fixes the problem.

**Comment by cfhammill** [comment]
I disabled clean-up while debugging and forgot to reinstantiate. Will add an argument defaulting to TRUE for whether to clean-up.
