### ISSUE TITLE
mincLmer returns only half the mask

### ISSUE THREAD

**Issue by DJFernandes** [Mouse-Imaging-Centre/RMINC#90]
mincLmer returns only half the mask after running. Below are commands that reproduce the error.
`
df=read.csv('/hpf/largeprojects/MICe/dfernandes/lqiu_long/growth_rates2/growth_rates_relative_det.csv')

maskfile="/hpf/largeprojects/MICe/dfernandes/lqiu_long/test_p65dc2/mask/mask_dimorder.mnc"

vs=mincLmer(formula='files~age*sex+(1|ID)',data=df,mask=maskfile,temp_dir="tmp",parallel=c('sge',8))

##number of rows in vs should equal number of voxels in mask
dim(vs)
#[1] 342636     10

sum(mincGetVolume(maskfile)>0.5)
#[1] 685269
`

**Comment by DJFernandes** [comment]
Issue not present in R 3.2.3
Issue present in R 3.1.1

**Comment by cfhammill** [comment]
Source of the bug is queued jobs dying with "No random effects terms specified in formula". Github search for the error message put it in mkReTrms which could be from the re-init code or in lFormula.

**Comment by cfhammill** [comment]
Issue did not replicate after updating lme4 with 3.1.1, and has not been observed on the now system-wide 3.3.1
