### ISSUE TITLE
Problems installing dependencies from BioConductor

### ISSUE THREAD

**Issue by gdevenyi** [Mouse-Imaging-Centre/RMINC#91]
I'm preparing a MINC VM auto-build which will include RMINC

I can't install the current release using install_url from devtools because descriptions is missing a dependency which has been fixed in HEAD

Thanks!

**Comment by cfhammill** [comment]
Which dependency is missing in the current release out of curiosity?

**Comment by gdevenyi** [comment]
Making this call:
install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz", dependencies=TRUE, repos='https://cloud.r-project.org/')

The installer eventually complains about BiocInstaller.

You fixed it here:
https://github.com/Mouse-Imaging-Centre/RMINC/commit/69231a60d5a76abee5792eb343ec29f2c1c452fa

**Comment by gdevenyi** [comment]
Here's the error, had to re-run my scripts:
```R
> install.packages("devtools", repos='https://cloud.r-project.org/')
> library(devtools)
> install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz", dependencies=TRUE, repos='https://cloud.r-project.org/')
#Skip much output of packages downloading/installing
Installing qvalue
Error: 'BiocInstaller' must be installed for this functionality.
Execution halted
```

**Comment by cfhammill** [comment]
Oh yes, something changed at the interface of R and BioConductor. I'll push a new release soon. Thanks for the catch.

**Comment by gdevenyi** [comment]
So, I just tried an install from github HEAD, it fails with the same error, this is on an entirely fresh R (running first time).

```R
install.packages("devtools", repos='https://cloud.r-project.org/')
library(devtools)
install_github("Mouse-Imaging-Centre/RMINC", dependencies=TRUE, repos='https://cloud.r-project.org/')
#Many dependencies
Installing qvalue
Error: 'BiocInstaller' must be installed for this functionality.
Execution halted
```

**Comment by cfhammill** [comment]
Hmm, bioConductor is making things complicated. Our CI builds are still passing, the difference may be in the repository options. 

you may need: 
```
repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc",  
          CRAN = "https://cloud.r-project.org")
```

It would be nice if this could be picked up automatically.

**Comment by cfhammill** [comment]
Can you give the install another try when you get a chance? I just tried a build on the r-devel docker image and it works so long as BiocInstaller is suggested and bioCsoft is in the repos.

**Comment by gdevenyi** [comment]
So, before I start the build, you're suggesting:

```R
repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc",  
          CRAN = "https://cloud.r-project.org")
install.packages("devtools")
library(devtools)
install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz", dependencies=TRUE)
```

Correct?

**Comment by cfhammill** [comment]
I was suggesting 

```
install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz",
            dependencies=TRUE, 
            repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc",  
                      CRAN = "https://cloud.r-project.org"))
```

Although your idea is probably cleaner, just needs to be wrapped in the options function:

```
options(repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc",  
                  CRAN = "https://cloud.r-project.org"))

packages("devtools")
library(devtools)
install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz", dependencies=TRUE)
```

**Comment by gdevenyi** [comment]
ah right, options. Thanks!

**Comment by gdevenyi** [comment]
Sadly, both options and explicitly didn't fix it:
```R
install.packages("devtools", repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc",
                  CRAN = "https://cloud.r-project.org"))
library(devtools)
install_url("https://github.com/Mouse-Imaging-Centre/RMINC/archive/v1.4.2.0.tar.gz", dependencies=TRUE,
            repos = c(bioCsoft = "http://bioconductor.org/packages/3.3/bioc", CRAN = "https://cloud.r-project.org"))
Installing qvalue
Error: 'BiocInstaller' must be installed for this functionality.
Execution halted
```

Finally had success actually using the third-party biocinstaller stuff...
```R
source("https://bioconductor.org/biocLite.R")
library(BiocInstaller)
install.packages("devtools", repos = 'https://cloud.r-project.org', dependencies=TRUE)
library(devtools)
install_url("$RMINC", repos = 'https://cloud.r-project.org', dependencies=TRUE)
quit()

```

**Comment by cfhammill** [comment]
Hi Gabe,

It looks like at least in the first case you are still pointing to the tarred release which does not have the BiocInstaller yet. Does the same hold true with the head of master branch?

**Comment by gdevenyi** [comment]
Yes, I wasn't able to get it working without explicitly pulling in bioconductor.

**Comment by cfhammill** [comment]
What OS is the VM, it would be nice if I could recreate the problem - it's building stably on Trusty, Mac OSX, and Debian stretch (I think). If it's one of those I'm not certain I'm not certain where the difference is.

**Comment by gdevenyi** [comment]
This is a Ubuntu 16.04 lubuntu system built up using packer,

Complete build scripts are at https://github.com/cobralab/MINC-VM

**Comment by gdevenyi** [comment]
FYI, install scripts are in flux as I slowly tackle my issues list.

This version works: https://github.com/CobraLab/MINC-VM/tree/335eb64e7b80e3791aca566dd7bc1855315a6aaf

Until this is fixed https://github.com/Mouse-Imaging-Centre/minc-stuffs/issues/28

**Comment by cfhammill** [comment]
Has this problem resolved in the more recent releases @gdevenyi?

**Comment by cfhammill** [comment]
Closing until this problem resurfaces (if it does)
