### ISSUE TITLE
Any objections to decreasing mincGetVolume verbosity?

### ISSUE THREAD

**Issue by cfhammill** [Mouse-Imaging-Centre/RMINC#96]
Currently mincGetVolume prints starts and counts for the volume being read in, it's a nice cue if there is a problem with a volume, but clutters the console when many volumes are read in.

Any objections to removing this, or making it optional?

**Comment by jasonlerch** [comment]
No objections from me.

Jason

On Aug 4, 2016, 10:36 AM -0400, Chris Hammill <notifications@github.com>, wrote:

Currently mincGetVolume prints starts and counts for the volume being read in, it's a nice cue if there is a problem with a volume, but clutters the console when many volumes are read in.

Any objections to removing this, or making it optional?
