### ISSUE TITLE
shiny interface does not recognize tlmer stat type

### ISSUE THREAD

**Issue by jasonlerch** [Mouse-Imaging-Centre/RMINC#97]
The shiny interface that can be launched from the R terminal determines the colour scheme (symmetric or not) based on the stat type. tlmer needs to be added as a recognized stats type

**Comment by cfhammill** [comment]
What's the rationale for having tlmer as it's own stat type?

**Comment by jasonlerch** [comment]
mincFDR uses it to warn users that they need to separately estimate DF or warns them that here be dragons regarding how DF are estimated.

Jason

On Aug 17, 2016, 3:06 PM -0400, Chris Hammill <notifications@github.com>, wrote:

What's the rationale for having tlmer as it's own stat type?

**Comment by cfhammill** [comment]
It looks to me as though it will issue that warning regardless, it does grep for "tlmer" columns though. For consistency it's probably best to leave the stat-type as tlmer, especially since it's primarily internal use anyway. I will make the change in the shiny applet.
